CREATE USER PROJETOINTEGRADOR IDENTIFIED BY 1234;
GRANT CONNECT TO PROJETOINTEGRADOR;
GRANT RESOURCE TO PROJETOINTEGRADOR;
GRANT UNLIMITED TABLESPACE TO PROJETOINTEGRADOR;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO PROJETOINTEGRADOR;