
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto_Integrador.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class ALUNO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ALUNO()
    {

        this.ALUNO_OBJETIVO = new HashSet<ALUNO_OBJETIVO>();

        this.TREINAMENTO = new HashSet<TREINAMENTO>();

        this.MEDICAO = new HashSet<MEDICAO>();

        this.FICHA = new HashSet<FICHA>();

        this.FICHA_SIGLA = new HashSet<FICHA_SIGLA>();

    }


    public long CPF_ALUNO { get; set; }

    public long CPF_FUNCIONARIO { get; set; }

    public bool STA_ALUNO { get; set; }



    public virtual PESSOA PESSOA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ALUNO_OBJETIVO> ALUNO_OBJETIVO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TREINAMENTO> TREINAMENTO { get; set; }

    public virtual FUNCIONARIO FUNCIONARIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MEDICAO> MEDICAO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FICHA> FICHA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FICHA_SIGLA> FICHA_SIGLA { get; set; }

}

}
