

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto_Integrador.Models.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ALUNO> ALUNO { get; set; }

    public virtual DbSet<ALUNO_OBJETIVO> ALUNO_OBJETIVO { get; set; }

    public virtual DbSet<CADASTRO_OBJETIVO> CADASTRO_OBJETIVO { get; set; }

    public virtual DbSet<EXERCICIO> EXERCICIO { get; set; }

    public virtual DbSet<FUNCAO> FUNCAO { get; set; }

    public virtual DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }

    public virtual DbSet<GRUPO_MUSCULAR> GRUPO_MUSCULAR { get; set; }

    public virtual DbSet<MEDICAO> MEDICAO { get; set; }

    public virtual DbSet<PESSOA> PESSOA { get; set; }

    public virtual DbSet<TREINAMENTO> TREINAMENTO { get; set; }

    public virtual DbSet<FICHA> FICHA { get; set; }

    public virtual DbSet<FICHA_SIGLA> FICHA_SIGLA { get; set; }

}

}

