//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrador.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FICHA()
        {
            this.FICHA_SIGLA = new HashSet<FICHA_SIGLA>();
            this.TREINAMENTO = new HashSet<TREINAMENTO>();
        }
    
        public long CPF_ALUNO { get; set; }
        public short COD_FICHA { get; set; }
        public Nullable<System.DateTime> DTAINI_FICHA { get; set; }
        public Nullable<System.DateTime> DTAFIM_FICHA { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_SIGLA> FICHA_SIGLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREINAMENTO> TREINAMENTO { get; set; }
    }
}
