
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto_Integrador.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class MEDICAO
{

    public long CPF_ALUNO { get; set; }

    public System.DateTime DAT_MEDICAO { get; set; }

    public long CPF_FUNCIONARIO { get; set; }

    public decimal PES_MEDICAO { get; set; }

    public decimal ALT_MEDICAO { get; set; }

    public decimal BUS_MEDICAO { get; set; }

    public decimal TOR_MEDICAO { get; set; }

    public decimal CIN_MEDICAO { get; set; }

    public decimal ABD_MEDICAO { get; set; }

    public decimal QUA_MEDICAO { get; set; }

    public decimal COE_MEDICAO { get; set; }

    public decimal COD_MEDICAO { get; set; }

    public decimal PAE_MEDICAO { get; set; }

    public decimal PAD_MEDICAO { get; set; }

    public decimal BRE_MEDICAO { get; set; }

    public decimal BRD_MEDICAO { get; set; }

    public decimal ANE_MEDICAO { get; set; }

    public decimal AND_MEDICAO { get; set; }



    public virtual ALUNO ALUNO { get; set; }

    public virtual FUNCIONARIO FUNCIONARIO { get; set; }

}

}
