//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Integrador.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREINAMENTO
    {
        public short COD_FICHA { get; set; }
        public short COD_EXERCICIO { get; set; }
        public long CPF_ALUNO { get; set; }
        public Nullable<short> REP_TREINAMENTO { get; set; }
        public Nullable<short> SER_TREINAMENTO { get; set; }
        public Nullable<short> CAR_TREINAMENTO { get; set; }
        public Nullable<short> TEM_TREINAMENTO { get; set; }
        public Nullable<short> PON_TREINAMENTO { get; set; }
        public Nullable<bool> STA_TREINAMENTO { get; set; }
        public Nullable<byte> QTD_REPET_TREINAMENTO { get; set; }
        public Nullable<byte> QTD_REPET_SIGLA { get; set; }
        public Nullable<byte> REP_FICHA { get; set; }
    
        public virtual EXERCICIO EXERCICIO { get; set; }
        public virtual FICHA FICHA { get; set; }
    }
}
